language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t theozpal/docker-react-test -f Dockerfile.dev .

script:
    - docker run -e CI=true theozpal/docker-react-test npm run test