language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t theozpal/docker-react-test -f Dockerfile.dev .

script:
    - docker run -e CI=true theozpal/docker-react-test npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react-test"
    env: "Docker-React-Test-env"
    bucket_list: "elasticbeanstalk-us-east-2-571485019874"
    bucket_path: "docker-react-test"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: 
        secure: $AWS_SECRET_KEY
